version: '3.9'

services:
  administratordb:
    container_name: 'administratordb'
    build:
      context: DockerScripts/Mssql
      dockerfile: Dockerfile
    ports:
      - ${MSSQL_PORT-1433}:1433
    environment:
      SA_PASSWORD: ${MSSQL_PASSWORD-Yourpassword123}
      MSSQL_DB: ${MSSQL_DB-TestDB}
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
volumes:
  sqldata: {}